//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestTravelIssued.TravelIssuedRequest", Namespace="http://schemas.datacontract.org/2004/07/FanavaranApiService")]
    public partial class RequestTravelIssuedTravelIssuedRequest : object
    {
        
        private TravelService.RequestTravelIssuedIssuingTravel IssuingTravelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TravelService.RequestTravelIssuedIssuingTravel IssuingTravel
        {
            get
            {
                return this.IssuingTravelField;
            }
            set
            {
                this.IssuingTravelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestTravelIssued.IssuingTravel", Namespace="http://schemas.datacontract.org/2004/07/FanavaranApiService")]
    public partial class RequestTravelIssuedIssuingTravel : object
    {
        
        private string CountryCodeField;
        
        private int CoverageField;
        
        private string DepositIdentityField;
        
        private int DurationField;
        
        private TravelService.DurationTravelKindEnum DurationTravelKindField;
        
        private string GregorianBirthDayField;
        
        private string GregorianBirthMonthField;
        
        private int GregorianBirthYearField;
        
        private TravelService.RequestTravelIssuedInsurer InsurerField;
        
        private string PassportNumberField;
        
        private string ReceiptDateField;
        
        private string ReceiptNumberField;
        
        private TravelService.TravelKindEnum TravelKindField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Coverage
        {
            get
            {
                return this.CoverageField;
            }
            set
            {
                this.CoverageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepositIdentity
        {
            get
            {
                return this.DepositIdentityField;
            }
            set
            {
                this.DepositIdentityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TravelService.DurationTravelKindEnum DurationTravelKind
        {
            get
            {
                return this.DurationTravelKindField;
            }
            set
            {
                this.DurationTravelKindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GregorianBirthDay
        {
            get
            {
                return this.GregorianBirthDayField;
            }
            set
            {
                this.GregorianBirthDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GregorianBirthMonth
        {
            get
            {
                return this.GregorianBirthMonthField;
            }
            set
            {
                this.GregorianBirthMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GregorianBirthYear
        {
            get
            {
                return this.GregorianBirthYearField;
            }
            set
            {
                this.GregorianBirthYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TravelService.RequestTravelIssuedInsurer Insurer
        {
            get
            {
                return this.InsurerField;
            }
            set
            {
                this.InsurerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNumber
        {
            get
            {
                return this.PassportNumberField;
            }
            set
            {
                this.PassportNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptDate
        {
            get
            {
                return this.ReceiptDateField;
            }
            set
            {
                this.ReceiptDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptNumber
        {
            get
            {
                return this.ReceiptNumberField;
            }
            set
            {
                this.ReceiptNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TravelService.TravelKindEnum TravelKind
        {
            get
            {
                return this.TravelKindField;
            }
            set
            {
                this.TravelKindField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestTravelIssued.Insurer", Namespace="http://schemas.datacontract.org/2004/07/FanavaranApiService")]
    public partial class RequestTravelIssuedInsurer : object
    {
        
        private string AddressField;
        
        private int BirthDayField;
        
        private int BirthMonthField;
        
        private int BirthYearField;
        
        private string FatherNameField;
        
        private TravelService.GenderTypeEnum GenderField;
        
        private string IdentityNumberField;
        
        private int IsIranianField;
        
        private string IssuedPlaceField;
        
        private string LastNameField;
        
        private string LatinAddressField;
        
        private string LatinLastNameField;
        
        private string LatinNameField;
        
        private int MBirthYearField;
        
        private string MobileField;
        
        private string NameField;
        
        private string NationalCodeField;
        
        private int NationalityField;
        
        private string PhoneNumberField;
        
        private string PostalCodeField;
        
        private string UnIranianCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BirthDay
        {
            get
            {
                return this.BirthDayField;
            }
            set
            {
                this.BirthDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BirthMonth
        {
            get
            {
                return this.BirthMonthField;
            }
            set
            {
                this.BirthMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BirthYear
        {
            get
            {
                return this.BirthYearField;
            }
            set
            {
                this.BirthYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherName
        {
            get
            {
                return this.FatherNameField;
            }
            set
            {
                this.FatherNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TravelService.GenderTypeEnum Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityNumber
        {
            get
            {
                return this.IdentityNumberField;
            }
            set
            {
                this.IdentityNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsIranian
        {
            get
            {
                return this.IsIranianField;
            }
            set
            {
                this.IsIranianField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuedPlace
        {
            get
            {
                return this.IssuedPlaceField;
            }
            set
            {
                this.IssuedPlaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LatinAddress
        {
            get
            {
                return this.LatinAddressField;
            }
            set
            {
                this.LatinAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LatinLastName
        {
            get
            {
                return this.LatinLastNameField;
            }
            set
            {
                this.LatinLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LatinName
        {
            get
            {
                return this.LatinNameField;
            }
            set
            {
                this.LatinNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MBirthYear
        {
            get
            {
                return this.MBirthYearField;
            }
            set
            {
                this.MBirthYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalCode
        {
            get
            {
                return this.NationalCodeField;
            }
            set
            {
                this.NationalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nationality
        {
            get
            {
                return this.NationalityField;
            }
            set
            {
                this.NationalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnIranianCode
        {
            get
            {
                return this.UnIranianCodeField;
            }
            set
            {
                this.UnIranianCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DurationTravelKindEnum", Namespace="http://schemas.datacontract.org/2004/07/BLL")]
    public enum DurationTravelKindEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Day = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SixMonths = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OneYear = 18,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TravelKindEnum", Namespace="http://schemas.datacontract.org/2004/07/BLL")]
    public enum TravelKindEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Multiple = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenderTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/BLL")]
    public enum GenderTypeEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Man = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Woman = 27,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/FanavaranApiService")]
    public partial class Response : object
    {
        
        private int CountOfTodayField;
        
        private TravelService.ErrorType ErrorField;
        
        private int RemainingRequestField;
        
        private int ResponseIdField;
        
        private string ResponseTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountOfToday
        {
            get
            {
                return this.CountOfTodayField;
            }
            set
            {
                this.CountOfTodayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TravelService.ErrorType Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemainingRequest
        {
            get
            {
                return this.RemainingRequestField;
            }
            set
            {
                this.RemainingRequestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseId
        {
            get
            {
                return this.ResponseIdField;
            }
            set
            {
                this.ResponseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseText
        {
            get
            {
                return this.ResponseTextField;
            }
            set
            {
                this.ResponseTextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorType", Namespace="http://schemas.datacontract.org/2004/07/BLL")]
    public enum ErrorType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotError = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrRecordNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginInvalidUser = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Safety = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSafety = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SourceServiceNotWork = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAccessToMethod = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InquiryParameterRequired = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InquiryOutOfMaxDailyRequest = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInIssude = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginInvalidUserInFanavaranService = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SomeErrors = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DBError = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MappingError = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IssuedError = 14,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestTravelIssued.CancelIssuedTravel", Namespace="http://schemas.datacontract.org/2004/07/FanavaranApiService")]
    public partial class RequestTravelIssuedCancelIssuedTravel : object
    {
        
        private string ActiveDateField;
        
        private System.Nullable<short> ChangekindField;
        
        private System.Nullable<short> ElhnoField;
        
        private int PolicyIdField;
        
        private string SeriField;
        
        private System.Nullable<int> SerialField;
        
        private string SodurDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveDate
        {
            get
            {
                return this.ActiveDateField;
            }
            set
            {
                this.ActiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Changekind
        {
            get
            {
                return this.ChangekindField;
            }
            set
            {
                this.ChangekindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Elhno
        {
            get
            {
                return this.ElhnoField;
            }
            set
            {
                this.ElhnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicyId
        {
            get
            {
                return this.PolicyIdField;
            }
            set
            {
                this.PolicyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seri
        {
            get
            {
                return this.SeriField;
            }
            set
            {
                this.SeriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SodurDate
        {
            get
            {
                return this.SodurDateField;
            }
            set
            {
                this.SodurDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestTravelIssued.TravelIssuedRequestList", Namespace="http://schemas.datacontract.org/2004/07/FanavaranApiService")]
    public partial class RequestTravelIssuedTravelIssuedRequestList : object
    {
        
        private TravelService.RequestTravelIssuedIssuingTravelList IssuingTravelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TravelService.RequestTravelIssuedIssuingTravelList IssuingTravel
        {
            get
            {
                return this.IssuingTravelField;
            }
            set
            {
                this.IssuingTravelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestTravelIssued.IssuingTravelList", Namespace="http://schemas.datacontract.org/2004/07/FanavaranApiService")]
    public partial class RequestTravelIssuedIssuingTravelList : object
    {
        
        private string CountryCodeField;
        
        private int CoverageField;
        
        private string DepositIdentityField;
        
        private int DurationField;
        
        private TravelService.DurationTravelKindEnum DurationTravelKindField;
        
        private string GregorianBirthDayField;
        
        private string GregorianBirthMonthField;
        
        private int GregorianBirthYearField;
        
        private TravelService.RequestTravelIssuedInsurer InsurerField;
        
        private string PassportNumberField;
        
        private string ReceiptDateField;
        
        private string ReceiptNumberField;
        
        private TravelService.TravelKindEnum TravelKindField;
        
        private int UniquIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Coverage
        {
            get
            {
                return this.CoverageField;
            }
            set
            {
                this.CoverageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepositIdentity
        {
            get
            {
                return this.DepositIdentityField;
            }
            set
            {
                this.DepositIdentityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TravelService.DurationTravelKindEnum DurationTravelKind
        {
            get
            {
                return this.DurationTravelKindField;
            }
            set
            {
                this.DurationTravelKindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GregorianBirthDay
        {
            get
            {
                return this.GregorianBirthDayField;
            }
            set
            {
                this.GregorianBirthDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GregorianBirthMonth
        {
            get
            {
                return this.GregorianBirthMonthField;
            }
            set
            {
                this.GregorianBirthMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GregorianBirthYear
        {
            get
            {
                return this.GregorianBirthYearField;
            }
            set
            {
                this.GregorianBirthYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TravelService.RequestTravelIssuedInsurer Insurer
        {
            get
            {
                return this.InsurerField;
            }
            set
            {
                this.InsurerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNumber
        {
            get
            {
                return this.PassportNumberField;
            }
            set
            {
                this.PassportNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptDate
        {
            get
            {
                return this.ReceiptDateField;
            }
            set
            {
                this.ReceiptDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptNumber
        {
            get
            {
                return this.ReceiptNumberField;
            }
            set
            {
                this.ReceiptNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TravelService.TravelKindEnum TravelKind
        {
            get
            {
                return this.TravelKindField;
            }
            set
            {
                this.TravelKindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UniquId
        {
            get
            {
                return this.UniquIdField;
            }
            set
            {
                this.UniquIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/BLL")]
    public enum CurrencyTypeEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rial = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dollar = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TravelService.IIssuedTravelService")]
    public interface IIssuedTravelService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/TravelIssued", ReplyAction="http://tempuri.org/IIssuedTravelService/TravelIssuedResponse")]
        System.Threading.Tasks.Task<TravelService.Response> TravelIssuedAsync(string UserName, string Password, TravelService.RequestTravelIssuedTravelIssuedRequest IssuedRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/CancelIssuedTravel", ReplyAction="http://tempuri.org/IIssuedTravelService/CancelIssuedTravelResponse")]
        System.Threading.Tasks.Task<TravelService.Response> CancelIssuedTravelAsync(string UserName, string Password, TravelService.RequestTravelIssuedCancelIssuedTravel CancelRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/TravelIssuedList", ReplyAction="http://tempuri.org/IIssuedTravelService/TravelIssuedListResponse")]
        System.Threading.Tasks.Task<TravelService.Response> TravelIssuedListAsync(string UserName, string Password, TravelService.RequestTravelIssuedTravelIssuedRequestList[] IssuedRequestList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/FindChangeKinds", ReplyAction="http://tempuri.org/IIssuedTravelService/FindChangeKindsResponse")]
        System.Threading.Tasks.Task<TravelService.Response> FindChangeKindsAsync(string UserName, string Password, System.Nullable<int> ChangeKindId, string ChangeKindName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/FindCountries", ReplyAction="http://tempuri.org/IIssuedTravelService/FindCountriesResponse")]
        System.Threading.Tasks.Task<TravelService.Response> FindCountriesAsync(string UserName, string Password, System.Nullable<int> CountryId, string CountryName, System.Nullable<int> PolicyKind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/FindZones", ReplyAction="http://tempuri.org/IIssuedTravelService/FindZonesResponse")]
        System.Threading.Tasks.Task<TravelService.Response> FindZonesAsync(string UserName, string Password, System.Nullable<int> ZoneId, string ZoneName, System.Nullable<int> PolicyKind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/FindLocation", ReplyAction="http://tempuri.org/IIssuedTravelService/FindLocationResponse")]
        System.Threading.Tasks.Task<TravelService.Response> FindLocationAsync(string UserName, string Password, System.Nullable<int> LocationId, string LocationName, System.Nullable<int> PolicyKind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/FindAgencies", ReplyAction="http://tempuri.org/IIssuedTravelService/FindAgenciesResponse")]
        System.Threading.Tasks.Task<TravelService.Response> FindAgenciesAsync(string UserName, string Password, System.Nullable<int> AgencyId, string AgencyName, System.Nullable<int> AgencyKindId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/FindTravelCoverageLimit", ReplyAction="http://tempuri.org/IIssuedTravelService/FindTravelCoverageLimitResponse")]
        System.Threading.Tasks.Task<TravelService.Response> FindTravelCoverageLimitAsync(string UserName, string Password, System.Nullable<int> PolicyKind, string Caption, string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/FindTravelLocationCoverageLimit", ReplyAction="http://tempuri.org/IIssuedTravelService/FindTravelLocationCoverageLimitResponse")]
        System.Threading.Tasks.Task<TravelService.Response> FindTravelLocationCoverageLimitAsync(string UserName, string Password, System.Nullable<int> PolicyKind, System.Nullable<int> LocationId, string LocationName, System.Nullable<int> CoverageId, string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/FindTravelPolicyCountryLocationZone", ReplyAction="http://tempuri.org/IIssuedTravelService/FindTravelPolicyCountryLocationZoneRespon" +
            "se")]
        System.Threading.Tasks.Task<TravelService.Response> FindTravelPolicyCountryLocationZoneAsync(string UserName, string Password, System.Nullable<int> PolicyKind, System.Nullable<int> Id, System.Nullable<int> ZoneId, System.Nullable<int> CountryId, System.Nullable<int> LocationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/FindContract", ReplyAction="http://tempuri.org/IIssuedTravelService/FindContractResponse")]
        System.Threading.Tasks.Task<TravelService.Response> FindContractAsync(string UserName, string Password, System.Nullable<int> PolicyKind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/TravelRate", ReplyAction="http://tempuri.org/IIssuedTravelService/TravelRateResponse")]
        System.Threading.Tasks.Task<TravelService.Response> TravelRateAsync(string UserName, string Password, TravelService.CurrencyTypeEnum Currency, System.Nullable<int> ZoneId, System.Nullable<int> Duration, System.Nullable<int> Age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/FindTravelRatePolicyCountryLocationZone", ReplyAction="http://tempuri.org/IIssuedTravelService/FindTravelRatePolicyCountryLocationZoneRe" +
            "sponse")]
        System.Threading.Tasks.Task<TravelService.Response> FindTravelRatePolicyCountryLocationZoneAsync(string UserName, string Password, TravelService.CurrencyTypeEnum Currency, int PolicyKind, System.Nullable<int> ZoneId, System.Nullable<int> LocationID, System.Nullable<int> CountryID, System.Nullable<int> Coverage, System.Nullable<int> Duration, System.Nullable<int> Age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/FindResponse", ReplyAction="http://tempuri.org/IIssuedTravelService/FindResponseResponse")]
        System.Threading.Tasks.Task<TravelService.Response> FindResponseAsync(string UserName, string Password, int ResponseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssuedTravelService/CheckSafety", ReplyAction="http://tempuri.org/IIssuedTravelService/CheckSafetyResponse")]
        System.Threading.Tasks.Task<TravelService.Response> CheckSafetyAsync(string UserName, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IIssuedTravelServiceChannel : TravelService.IIssuedTravelService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class IssuedTravelServiceClient : System.ServiceModel.ClientBase<TravelService.IIssuedTravelService>, TravelService.IIssuedTravelService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IssuedTravelServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(IssuedTravelServiceClient.GetBindingForEndpoint(endpointConfiguration), IssuedTravelServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IssuedTravelServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IssuedTravelServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IssuedTravelServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IssuedTravelServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IssuedTravelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> TravelIssuedAsync(string UserName, string Password, TravelService.RequestTravelIssuedTravelIssuedRequest IssuedRequest)
        {
            return base.Channel.TravelIssuedAsync(UserName, Password, IssuedRequest);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> CancelIssuedTravelAsync(string UserName, string Password, TravelService.RequestTravelIssuedCancelIssuedTravel CancelRequest)
        {
            return base.Channel.CancelIssuedTravelAsync(UserName, Password, CancelRequest);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> TravelIssuedListAsync(string UserName, string Password, TravelService.RequestTravelIssuedTravelIssuedRequestList[] IssuedRequestList)
        {
            return base.Channel.TravelIssuedListAsync(UserName, Password, IssuedRequestList);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> FindChangeKindsAsync(string UserName, string Password, System.Nullable<int> ChangeKindId, string ChangeKindName)
        {
            return base.Channel.FindChangeKindsAsync(UserName, Password, ChangeKindId, ChangeKindName);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> FindCountriesAsync(string UserName, string Password, System.Nullable<int> CountryId, string CountryName, System.Nullable<int> PolicyKind)
        {
            return base.Channel.FindCountriesAsync(UserName, Password, CountryId, CountryName, PolicyKind);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> FindZonesAsync(string UserName, string Password, System.Nullable<int> ZoneId, string ZoneName, System.Nullable<int> PolicyKind)
        {
            return base.Channel.FindZonesAsync(UserName, Password, ZoneId, ZoneName, PolicyKind);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> FindLocationAsync(string UserName, string Password, System.Nullable<int> LocationId, string LocationName, System.Nullable<int> PolicyKind)
        {
            return base.Channel.FindLocationAsync(UserName, Password, LocationId, LocationName, PolicyKind);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> FindAgenciesAsync(string UserName, string Password, System.Nullable<int> AgencyId, string AgencyName, System.Nullable<int> AgencyKindId)
        {
            return base.Channel.FindAgenciesAsync(UserName, Password, AgencyId, AgencyName, AgencyKindId);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> FindTravelCoverageLimitAsync(string UserName, string Password, System.Nullable<int> PolicyKind, string Caption, string Value)
        {
            return base.Channel.FindTravelCoverageLimitAsync(UserName, Password, PolicyKind, Caption, Value);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> FindTravelLocationCoverageLimitAsync(string UserName, string Password, System.Nullable<int> PolicyKind, System.Nullable<int> LocationId, string LocationName, System.Nullable<int> CoverageId, string Value)
        {
            return base.Channel.FindTravelLocationCoverageLimitAsync(UserName, Password, PolicyKind, LocationId, LocationName, CoverageId, Value);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> FindTravelPolicyCountryLocationZoneAsync(string UserName, string Password, System.Nullable<int> PolicyKind, System.Nullable<int> Id, System.Nullable<int> ZoneId, System.Nullable<int> CountryId, System.Nullable<int> LocationId)
        {
            return base.Channel.FindTravelPolicyCountryLocationZoneAsync(UserName, Password, PolicyKind, Id, ZoneId, CountryId, LocationId);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> FindContractAsync(string UserName, string Password, System.Nullable<int> PolicyKind)
        {
            return base.Channel.FindContractAsync(UserName, Password, PolicyKind);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> TravelRateAsync(string UserName, string Password, TravelService.CurrencyTypeEnum Currency, System.Nullable<int> ZoneId, System.Nullable<int> Duration, System.Nullable<int> Age)
        {
            return base.Channel.TravelRateAsync(UserName, Password, Currency, ZoneId, Duration, Age);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> FindTravelRatePolicyCountryLocationZoneAsync(string UserName, string Password, TravelService.CurrencyTypeEnum Currency, int PolicyKind, System.Nullable<int> ZoneId, System.Nullable<int> LocationID, System.Nullable<int> CountryID, System.Nullable<int> Coverage, System.Nullable<int> Duration, System.Nullable<int> Age)
        {
            return base.Channel.FindTravelRatePolicyCountryLocationZoneAsync(UserName, Password, Currency, PolicyKind, ZoneId, LocationID, CountryID, Coverage, Duration, Age);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> FindResponseAsync(string UserName, string Password, int ResponseId)
        {
            return base.Channel.FindResponseAsync(UserName, Password, ResponseId);
        }
        
        public System.Threading.Tasks.Task<TravelService.Response> CheckSafetyAsync(string UserName, string Password)
        {
            return base.Channel.CheckSafetyAsync(UserName, Password);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIssuedTravelService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IIssuedTravelService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIssuedTravelService))
            {
                return new System.ServiceModel.EndpointAddress("http://dfs.dayins.com/IssuedTravelService");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IIssuedTravelService))
            {
                return new System.ServiceModel.EndpointAddress("https://dfs.dayins.com/IssuedTravelService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IIssuedTravelService,
            
            BasicHttpsBinding_IIssuedTravelService,
        }
    }
}
